package com.sweet.market.store.migration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.UUID;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.configuration.FluentConfiguration;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.TestMethodOrder;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
@TestMethodOrder(OrderAnnotation.class)
class StoreMigrationTest {

    @Container
    static final PostgreSQLContainer<?> POSTGRESQL = new PostgreSQLContainer<>("postgres:17-alpine")
            .withDatabaseName("store_migration_test")
            .withUsername("market")
            .withPassword("market");

    @Test
    @org.junit.jupiter.api.Order(2)
    void 기존_판매자별_상점으로_상품_주문을_이관하고_사업자_상점은_소유자당_하나만_생성된다() throws SQLException {
        try (Connection connection = DriverManager.getConnection(
                POSTGRESQL.getJdbcUrl(),
                POSTGRESQL.getUsername(),
                POSTGRESQL.getPassword()
        )) {
            connection.createStatement().execute("""
                    CREATE TABLE members (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nickname VARCHAR(30) NOT NULL,
                        role VARCHAR(20) NOT NULL
                    )
                    """);
            connection.createStatement().execute("""
                    CREATE TABLE products (
                        id BIGINT PRIMARY KEY,
                        seller_id BIGINT NOT NULL,
                        status VARCHAR(20) NOT NULL DEFAULT 'ON_SALE'
                    )
                    """);
            connection.createStatement().execute("""
                    CREATE TABLE orders (
                        id BIGINT PRIMARY KEY,
                        product_id BIGINT NOT NULL
                    )
                    """);
            connection.createStatement().execute("""
                    CREATE TABLE stores (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        owner_member_id BIGINT NOT NULL,
                        type VARCHAR(20) NOT NULL,
                        public_name VARCHAR(100) NOT NULL,
                        introduction VARCHAR(2000) NOT NULL,
                        legal_business_name VARCHAR(120),
                        business_registration_id VARCHAR(40),
                        status VARCHAR(20) NOT NULL,
                        rejection_reason VARCHAR(1000),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            connection.createStatement().execute("""
                    INSERT INTO members (id, nickname, role) VALUES (1, '판매자', 'MEMBER')
                    """);
            connection.createStatement().execute("""
                    INSERT INTO members (id, nickname, role) VALUES (2, '관리자 판매자', 'ADMIN')
                    """);
            connection.createStatement().execute("INSERT INTO products (id, seller_id) VALUES (10, 1)");
            connection.createStatement().execute("INSERT INTO products (id, seller_id) VALUES (20, 2)");
            connection.createStatement().execute("INSERT INTO orders (id, product_id) VALUES (100, 10)");
            connection.createStatement().execute("INSERT INTO orders (id, product_id) VALUES (200, 20)");
            connection.createStatement().execute("""
                    INSERT INTO stores (id, owner_member_id, type, public_name, introduction, status)
                    VALUES (50, 1, 'PERSONAL', '기존 판매자 상점', '', 'ACTIVE')
                    """);
        }

        Flyway flyway = Flyway.configure()
                .dataSource(POSTGRESQL.getJdbcUrl(), POSTGRESQL.getUsername(), POSTGRESQL.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load();
        flyway.migrate();
        flyway.migrate();

        try (Connection connection = DriverManager.getConnection(
                POSTGRESQL.getJdbcUrl(),
                POSTGRESQL.getUsername(),
                POSTGRESQL.getPassword()
        )) {
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM stores WHERE type = 'PERSONAL'"))
                    .isEqualTo(2);
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM stores WHERE id = 50 AND owner_member_id = 1"))
                    .isEqualTo(1);
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM store_memberships WHERE role = 'OWNER' AND active"))
                    .isEqualTo(2);
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM products WHERE id = 10 AND store_id = 50"))
                    .isEqualTo(1);
            assertThat(queryLong(connection, """
                    SELECT COUNT(*)
                    FROM products p
                    JOIN stores s ON p.store_id = s.id
                    WHERE p.id = 20 AND s.owner_member_id = 2
                    """))
                    .isEqualTo(1);
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM orders WHERE id IN (100, 200) AND seller_id IN (1, 2)"))
                    .isEqualTo(2);
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM stores WHERE version = 0"))
                    .isEqualTo(2);
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM products WHERE store_id IS NULL"))
                    .isZero();
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM information_schema.columns "
                    + "WHERE table_name = 'products' AND column_name = 'seller_id'"))
                    .isZero();
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM pg_indexes "
                    + "WHERE tablename = 'products' AND indexname = 'idx_products_store_status_id'"))
                    .isEqualTo(1);

            connection.createStatement().execute("""
                    INSERT INTO stores (owner_member_id, type, public_name, introduction, status)
                    VALUES (1, 'BUSINESS', '첫 사업자 상점', '', 'PENDING')
                    """);
            assertThatThrownBy(() -> connection.createStatement().execute("""
                    INSERT INTO stores (owner_member_id, type, public_name, introduction, status)
                    VALUES (1, 'BUSINESS', '중복 사업자 상점', '', 'PENDING')
                    """))
                    .isInstanceOf(SQLException.class);
        }
    }

    @Test
    @org.junit.jupiter.api.Order(1)
    void 중복_사업자_상점이_있는_업그레이드는_데이터를_보존하고_중단한다() throws SQLException {
        String schema = "business_upgrade_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection connection = DriverManager.getConnection(
                POSTGRESQL.getJdbcUrl(), POSTGRESQL.getUsername(), POSTGRESQL.getPassword()
        )) {
            connection.createStatement().execute("CREATE SCHEMA " + schema);
            connection.createStatement().execute("""
                    CREATE TABLE %s.members (
                        id BIGINT PRIMARY KEY,
                        nickname VARCHAR(30) NOT NULL,
                        role VARCHAR(20) NOT NULL
                    )
                    """.formatted(schema));
            connection.createStatement().execute("""
                    INSERT INTO %s.members (id, nickname, role) VALUES (1, '기존 회원', 'MEMBER')
                    """.formatted(schema));
        }
        Flyway versionOne = configureFlyway(schema).target("1").load();
        versionOne.migrate();

        try (Connection connection = DriverManager.getConnection(
                POSTGRESQL.getJdbcUrl(),
                POSTGRESQL.getUsername(),
                POSTGRESQL.getPassword()
        )) {
            connection.createStatement().execute("""
                    INSERT INTO %s.stores (owner_member_id, type, public_name, introduction, status)
                    VALUES (1, 'BUSINESS', '기존 사업자 상점 1', '', 'PENDING'),
                           (1, 'BUSINESS', '기존 사업자 상점 2', '', 'PENDING')
                    """.formatted(schema));

            assertThatThrownBy(() -> configureFlyway(schema).load().migrate())
                    .isInstanceOf(FlywayException.class)
                    .hasMessageContaining("Duplicate BUSINESS stores");
            assertThat(queryLong(connection, "SELECT COUNT(*) FROM %s.stores WHERE type = 'BUSINESS'".formatted(schema)))
                    .isEqualTo(2);
        } finally {
            try (Connection connection = DriverManager.getConnection(
                    POSTGRESQL.getJdbcUrl(), POSTGRESQL.getUsername(), POSTGRESQL.getPassword()
            )) {
                connection.createStatement().execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    private FluentConfiguration configureFlyway(String schema) {
        return Flyway.configure()
                .dataSource(POSTGRESQL.getJdbcUrl(), POSTGRESQL.getUsername(), POSTGRESQL.getPassword())
                .schemas(schema)
                .defaultSchema(schema)
                .createSchemas(true)
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .locations("classpath:db/migration");
    }

    private long queryLong(Connection connection, String sql) throws SQLException {
        try (var statement = connection.createStatement(); var resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }
}
