package com.sweet.market.order.domain;

import com.sweet.market.common.domain.error.DomainError;

public enum OrderDomainError implements DomainError {
    PRODUCT_NOT_PURCHASABLE, CANCELLATION_NOT_ALLOWED, PAYMENT_NOT_ALLOWED,
    PAID_ORDER_CANCELLATION_NOT_ALLOWED, SHIPPING_NOT_ALLOWED,
    DELIVERY_COMPLETION_NOT_ALLOWED, REFUND_REQUEST_NOT_ALLOWED,
    REFUND_NOT_ALLOWED, REFUND_REJECTION_NOT_ALLOWED, CONFIRMATION_NOT_ALLOWED
}
