import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { couponQueryKeys, getStoreCouponCampaign, transitionStoreCouponCampaign, updateStoreCouponCampaign } from '../features/coupons/couponApi';
import { getOperableStores, getStoreCatalogProducts, storeOperationQueryKeys } from '../features/stores/storeOperationsApi';
import { EmptyState, ErrorState, StatusBadge } from '../shared/ui/ResourceStates';
import { parsePositiveIntegerParam } from '../shared/utils/parseId';
import { CouponCampaignAccessState, CouponCampaignForm, discountText, errorMessage, formatDate, invalidateCoupons, issueAvailabilityText, money } from './CouponCampaignWorkspacePage';

export function CouponCampaignDetailPage() {
  const { storeId, campaignId } = useParams(); const parsedStoreId = parsePositiveIntegerParam(storeId); const parsedCampaignId = parsePositiveIntegerParam(campaignId); const valid = parsedStoreId !== null && parsedCampaignId !== null; const client = useQueryClient();
  const storesQuery = useQuery({ queryKey: storeOperationQueryKeys.stores(), queryFn: getOperableStores });
  const store = (storesQuery.data ?? []).find((item) => item.storeId === parsedStoreId && item.type === 'BUSINESS' && item.role === 'OWNER' && item.status === 'ACTIVE');
  const campaignQuery = useQuery({ queryKey: couponQueryKeys.storeDetail(parsedStoreId ?? 0, parsedCampaignId ?? 0), queryFn: () => getStoreCouponCampaign(parsedStoreId ?? 0, parsedCampaignId ?? 0), enabled: valid && store !== undefined });
  const productsQuery = useQuery({ queryKey: storeOperationQueryKeys.productList(parsedStoreId ?? 0, { sort: 'NEWEST', page: 0, size: 100 }), queryFn: () => getStoreCatalogProducts(parsedStoreId ?? 0, { sort: 'NEWEST', page: 0, size: 100 }), enabled: store !== undefined });
  const updateMutation = useMutation({ mutationFn: (input: Parameters<typeof updateStoreCouponCampaign>[2]) => updateStoreCouponCampaign(parsedStoreId ?? 0, parsedCampaignId ?? 0, input), onSuccess: () => invalidateCoupons(client, parsedStoreId ?? undefined) });
  const transitionMutation = useMutation({ mutationFn: (action: 'schedule' | 'pause' | 'resume' | 'end') => transitionStoreCouponCampaign(parsedStoreId ?? 0, parsedCampaignId ?? 0, action), onSuccess: () => invalidateCoupons(client, parsedStoreId ?? undefined) });
  if (!valid) return <ErrorState message="쿠폰 캠페인 주소가 올바르지 않습니다." />;
  if (storesQuery.isLoading) return <p className="status-text">쿠폰 운영 권한을 확인하고 있습니다.</p>;
  if (storesQuery.error) return <ErrorState message={errorMessage(storesQuery.error, '상점 정보를 불러오지 못했습니다.')} />;
  if (!store) return <CouponCampaignAccessState />;
  if (campaignQuery.isLoading) return <p className="status-text">쿠폰 캠페인을 불러오고 있습니다.</p>;
  if (campaignQuery.error) return <ErrorState message={errorMessage(campaignQuery.error, '쿠폰 캠페인을 불러오지 못했습니다.')} />;
  if (!campaignQuery.data) return <EmptyState title="쿠폰 캠페인을 찾을 수 없습니다" />;
  const campaign = campaignQuery.data;
  const initialValue = { scope: campaign.scope, discountType: campaign.discountType, discountValue: campaign.discountValue, maxDiscountAmount: campaign.maxDiscountAmount ?? undefined, minimumPurchaseAmount: campaign.minimumPurchaseAmount, stackable: campaign.stackable, title: campaign.title, label: campaign.label ?? undefined, issueStartsAt: campaign.issueStartsAt, issueEndsAt: campaign.issueEndsAt, issueLimit: campaign.issueLimit ?? undefined, validityType: campaign.validityType, commonExpiresAt: campaign.commonExpiresAt ?? undefined, validityDays: campaign.validityDays ?? undefined, productIds: campaign.targets?.map((target) => target.productId) ?? [] };
  return <main className="coupon-workspace"><section className="coupon-workspace-header"><div><p className="eyebrow">COUPON DETAIL</p><h1>{campaign.title}</h1><p>{store.publicName} · 발급 {formatDate(campaign.issueStartsAt)} ~ {formatDate(campaign.issueEndsAt)}</p></div><Link className="text-button" to="/me/store/coupons">목록으로</Link></section><section className="coupon-panel"><div className="coupon-detail-status"><StatusBadge status={campaign.effectiveStatus} /><strong>{discountText(campaign)}</strong><span>최소 구매 {money(campaign.minimumPurchaseAmount)}원 · {campaign.stackable ? '중복 적용 가능' : '중복 적용 불가'}</span><span>{issueAvailabilityText(campaign)}</span></div><div className="coupon-lifecycle-actions">{campaign.lifecycleStatus === 'DRAFT' ? <button className="text-button" type="button" disabled={transitionMutation.isPending} onClick={() => transitionMutation.mutate('schedule')}>예약 시작</button> : null}{campaign.lifecycleStatus === 'SCHEDULED' ? <button className="text-button" type="button" disabled={transitionMutation.isPending} onClick={() => transitionMutation.mutate('pause')}>일시 중지</button> : null}{campaign.lifecycleStatus === 'PAUSED' ? <button className="text-button" type="button" disabled={transitionMutation.isPending} onClick={() => transitionMutation.mutate('resume')}>재개</button> : null}{campaign.lifecycleStatus !== 'ENDED' ? <button className="text-button danger-button" type="button" disabled={transitionMutation.isPending} onClick={() => transitionMutation.mutate('end')}>종료</button> : null}{transitionMutation.error ? <p className="error-text">{errorMessage(transitionMutation.error, '쿠폰 상태를 변경하지 못했습니다.')}</p> : null}</div>{campaign.targets?.length ? <section className="coupon-target-summary"><h2>대상 상품</h2><ul>{campaign.targets.map((target) => <li key={target.productId}>{target.title} · {money(target.price)}원</li>)}</ul></section> : null}<section className="coupon-edit-section"><div><p className="eyebrow">EDIT</p><h2>쿠폰 캠페인 수정</h2><p>초안 상태에서만 할인 조건과 발급 기간을 수정할 수 있습니다.</p></div><CouponCampaignForm products={productsQuery.data?.content ?? []} initialValue={initialValue} pending={updateMutation.isPending} disabled={campaign.lifecycleStatus !== 'DRAFT'} error={updateMutation.error} submitLabel="수정 저장" onSubmit={(input) => updateMutation.mutate(input)} /></section></section></main>;
}
