spring:
  config:
    activate:
      on-profile: performance-fixture

market:
  performance-fixture:
    version: m30-v1
    random-seed: 310031
    instant: 2026-07-17T00:00:00Z
    initialize: true
