package com.sweet.market.product.domain;

import com.sweet.market.common.domain.error.DomainError;

enum ProductDomainError implements DomainError {
    IMAGE_NOT_FOUND, IMAGE_REQUIRED, IMAGE_LIMIT_EXCEEDED,
    REPRESENTATIVE_IMAGE_COUNT_INVALID, IMAGE_SORT_ORDER_DUPLICATE,
    CHANGE_NOT_ALLOWED, NOT_HIDDEN, NOT_ON_SALE, NOT_RESERVED,
    STOCK_SETTINGS_UNAVAILABLE, LOW_STOCK_THRESHOLD_INVALID,
    SALES_POLICY_REQUIRED, SINGLE_ITEM_STOCK_SETTINGS_INVALID,
    INITIAL_STOCK_QUANTITY_INVALID
}
